### ISSUE TITLE
harden DNSRecord clean up when namespaces deleted

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/dns-operator#106]
**What**

Sometimes it seems possible for the `ManagedZone` to get deleted before the DNSRecords are removed. Seems we need to make sure the DNSRecords are removed before removing any finalizers on other objects (secrets, zones etc).

review event trigger relationships between all objects, (e.g. if mz secret is changed reconcile mz and related dns records).

Objects to consider:
- secret for managed zone
- managed zone
- dns policies
- dns records

If DNS Record or DNS Policy is deleting and the secret is absent, the DNS Record or DNS Policy should not have it's finalizer removed. 

DNS Record finalizers should only be removed if the controller has confirmed removal of those records from the provider.

If a DNS Record or Policy reconciles and the secret is absent, take actions:
- A clear log entry
- Emit a metric
- Investigate - Can we update status on namespace in this scenario.

**Comment by philbrookes** [comment]
PR: https://github.com/Kuadrant/dns-operator/pull/156
