### ISSUE TITLE
Improve validations on DNSRecord spec fields

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/dns-operator#110]
**What**

Improve the validations we currently have for fields on the DNSRecord spec. 

Review the DNSRecord spec and check that each field exposed via the public API has appropriate validations added.  
We may want to add a limit to the number of endpoints that can be added to the spec, we need to look into CEL docs to see what sort of upper limits are permitted.

Investigate more advanced CEL validations, can this whole [validate method](https://github.com/Kuadrant/dns-operator/blob/main/api/v1alpha1/dnsrecord_types.go#L175) be replaced with [CEL](https://kubernetes.io/docs/reference/using-api/cel/) validations?

**Comment by makslion** [comment]
Closing this issue. We can't conveniently use CEL validations unless we reimplement the Endpoint struct from external-dns. Reimplementing will allow us to reduce complexity of the CEL validation, otherwise openAPIV3Schema validation fails. Refer to the #158 for more details.

**Comment by mikenairn** [comment]
> Closing this issue. We can't conveniently use CEL validations unless we reimplement the Endpoint struct from external-dns. Reimplementing will allow us to reduce complexity of the CEL validation, otherwise openAPIV3Schema validation fails. Refer to the #158 for more details.

Using CEL to replace the validate function was only part of what we wanted to get out of this issue, and was really a question to answer as part of looking into the validation rather than being the only thing to try and do. 

The main thing was to "Improve the validations we currently have for fields on the DNSRecord spec". There is still a lot for the fields in the spec that have no validations where there probably should be something. HealthCheck spec in particular is quite lacking https://github.com/Kuadrant/dns-operator/blob/main/api/v1alpha1/dnsrecord_types.go#L27-L53
