### ISSUE TITLE
Add audit logs for actions taken against a given zone

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/dns-operator#117]
**What**

With multiple DNS controllers and even with just a single one, in order to debug and be able to understand what happened with a given zone we should ensure we some structured logging in place that uses the 
zoneid, 
DNSName
the cluster / owner id, 
the DNSPolicy (name and namespace that triggered the change (poss has to be done in kuadrant operator or could be covered by ownerid?). There could be optional meta data added by the DNSPolicy controller that if present should make it into logs?
The event that triggered it, the action taken and the resulting response. 

Ideally the outcome would be a set of logs that could be sent to a centralised logging system and then interrogated to understand what happened to a given zone by any controller instance that acted on it 

**use case**

I want to be able to diagnose and understand the set of actions taken in my DNS provider by the Kuadrant dns operator for a given zone or dns name. I want to be able to filter down in the logs to just actions taken against the dns provider that would have impacted the records in a given zone.

**Done**

- [ ] Log metadata defined and documented
- [ ] Logging reviewed in the controllers and providers updated 
- [ ] Logs tested in an aggregator for ability to filter down and find useful information
- [ ] Have a think about how to ensure logs have correct meta data (key values) (https://grafana.com/docs/loki/latest/query/logcli/)

**Comment by maleck13** [comment]
@makslion I believe this is in review now?

**Comment by makslion** [comment]
> @makslion I believe this is in review now?

I still consider it to be WIP. I'll move it to the "in review" once I'll be confident in changes. Right now I'm just looking for a feedback

**Comment by philbrookes** [comment]
https://github.com/Kuadrant/dns-operator/pull/197
