### ISSUE TITLE
Azure provider [Epic]

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/dns-operator#12]
**What**

Add a DNS Provider for Azure 

More details on Azure can be found here https://github.com/Kuadrant/multicluster-gateway-controller/blob/main/docs/proposals/assets/multiple-dns-provider-support/azure/azure.md

**Unknowns**
- GEO and weighted support will be more complex (additional ressource  required)
- https://github.com/Kuadrant/dns-operator/issues/12

- [x] #173
- [x] #174
- [x] #199 
- [x] #198 
- [x] #175
- [x] https://github.com/Kuadrant/dns-operator/issues/223
- [x] #224

**Comment by maleck13** [comment]
Is blocked by https://github.com/Kuadrant/dns-operator/issues/105

**Comment by maleck13** [comment]
THis is complete right @philbrookes
