### ISSUE TITLE
Update logging of external-dns code

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/dns-operator#124]
**What**

We currently have code copied and modified from external-dns which uses the logrus logger. We don't really want to change this since we hope to eventually remove it , but we do need all the logs it produces to go through the same logger as everything else in the dns operator.

**How**

Use a hook and catch all logrus logs and pass them to the dns operator logs?

**Comment by maleck13** [comment]
related to https://github.com/Kuadrant/dns-operator/issues/117 
Need to understand what is possible with adding our own metadata to external-dns logs
