### ISSUE TITLE
Accept a cluster id to the provider secret and use as part of the record structure

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/dns-operator#17]
The providerSecret used in a DNSPolicy currently provides the credentials required to access and edit a zone in a Cloud DNS Provider. This is also where we will be storing some configuration details about how the DNS Operator should interact with the zones referenced in this secret.

One of these values is the clusterID. This will be optionally present and indicate the local clusters ID when generating DNS Records. When this field is present it will also indicate that the zone file is a potentially distributed zone file, meaning that the various features required for this will need to be enabled for these zones, in other words, treating the zone as the authority rather than the local DNSRecord CRs, and being aware of remote health checks.

Although it may not end up as part of this task, it should be mentioned that anywhere this clusterID is used in the DNSRecords (either in the health check TXT record, or in the hostnames) it should be hashed to produce a short unique code that will always be the same value.

**Comment by maleck13** [comment]
@philbrookes need to add these issues to the kaudrant project and set the feature field
