### ISSUE TITLE
Add strategy conflict test case

### ISSUE THREAD

**Issue by mikenairn** [Kuadrant/dns-operator#182]
Expand on the test cases to cover expected conflicts such as a load balanced and simple strategy having been used.

Wait until https://github.com/Kuadrant/dns-operator/issues/187 is complete.

**Comment by maleck13** [comment]
@mikenairn is there still value in keeping the Kuadrant Operator test but ensuring it is simply validating that the status in the DNSPolicy resource is correct given it is the user facing API?

**Comment by mikenairn** [comment]
> @mikenairn is there still value in keeping the Kuadrant Operator test but ensuring it is simply validating that the status in the DNSPolicy resource is correct given it is the user facing API?

I think this should be a test we have in the kuadrant operator DNSPolicy tests even if it is tested at the DNSRecord level in the dns operator suite.

**Comment by makslion** [comment]
the test was added in https://github.com/Kuadrant/kuadrant-operator/pull/699 PR (issue https://github.com/Kuadrant/kuadrant-operator/issues/606 ). During #187, it will be almost unchanged. 
The test creates conflicting policies and makes sure we display errors in statuses of Policies and Records. I'll close this issue as there is not work to be done
