### ISSUE TITLE
DNSRecord constantly updates on default GEO conflict

### ISSUE THREAD

**Issue by averevki** [Kuadrant/dns-operator#265]
I can't get to a consistent state after causing a default geo conflict with DNS policies. Both policies are rapidly changing their state from not enforced to successfully enforced and back. The AWS default geo record also switches values every few seconds. No success even after waiting for 30min. DNS Operator logs also show reconciliation attempt every few seconds.

Kuadrant catalog image: `nightly-08-10-2024` DNS Operator image tag: `d0cab9eecbdb6f22b32371e85496018d5bd03090`

Related/Same as #210

**Comment by philbrookes** [comment]
Related/Same as https://github.com/Kuadrant/dns-operator/issues/210
