### ISSUE TITLE
Update GUID logic in Kuadrant-operator

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/dns-operator#28]
Currently the DNS Operator builds the LB CNAME with a guid based on the name of the gateway, as this could potentially be different on different clusters, this will need to be updated to generate based on the zone's root hostname, to ensure it is consistently generated on all clusters that interact with this zone.

**Comment by mikenairn** [comment]
Wrong repo, moved to https://github.com/Kuadrant/kuadrant-operator/issues/451
