### ISSUE TITLE
DNS records are re-created even if heath check is failing

### ISSUE THREAD

**Issue by trepel** [Kuadrant/dns-operator#319]
I scaled down my backend so that my DNS heath_check started failing. I manually removed the DNS records from cloud provider (AWS in my case). The records were re-created in AWS.

Unclear if this is the desired behavior or not, discussion needed.

**Comment by maleck13** [comment]
nice this is what we will document so!

**Comment by maleck13** [comment]
https://github.com/Kuadrant/kuadrant-operator/pull/1051
