### ISSUE TITLE
Record clashing DNS Policy configs that are overwriting each other.

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/dns-operator#40]
If an existing record for any host is a non-matching type (e.g. A record when we expect CNAME), then emit an error and a metric, and update the status of the DNS Record.

- [x] Report the error in of a DNS clash in the DNSRecord status
- [ ] Aggregate ready condition for DNSRecord to related DNSPolicy

**Comment by maleck13** [comment]
So for example if we have a.b.com and when we read the zone and that record is set to an A record and the current instance of the dns operator expects it to be a CNAME then it is an error scenerio.

**Comment by philbrookes** [comment]
Is there an easy way to recreate this? It should be resolved now, but I would like to confirm. ping @maleck13 @mikenairn @makslion

**Comment by maleck13** [comment]
Should be possible with a simple and loadbalanced policy on a shared gateway

**Comment by maleck13** [comment]
@philbrookes where are we at with this issue? I see an item still open but not sure it is upto date
