### ISSUE TITLE
Add rootHost to DNS Record spec

### ISSUE THREAD

**Issue by philbrookes** [Kuadrant/dns-operator#50]
**What** 

Add new optional field to the DNSRecord spec called "rootHost" and update DNSRecord creation to set that as the listener hostname.

If that field is present, all hosts in that DNS Record must be either subdomains of the rootHost or be the rootHost.

**Comment by maleck13** [comment]
hmm so I am thinking we add the optional property first then we might want to bump a release of dns operator? then update Kuadrant Operator?
