### ISSUE TITLE
Add support for private AWS hosted zones

### ISSUE THREAD

**Issue by trepel** [Kuadrant/dns-operator#61]
Private hosted zone can look like this
```
aws route53 get-hosted-zone --id=Z01234567T8N9RVU0NABC
{
    "HostedZone": {
        "Id": "/hostedzone/Z01234567T8N9RVU0NABC",
        "Name": "abc.def.com.",
        "CallerReference": "terraform-20240319062238790500000003",
        "Config": {
            "Comment": "Dev Managed Zone",
            "PrivateZone": true
        },
        "ResourceRecordSetCount": 5
    },
    "VPCs": [
        {
            "VPCRegion": "us-east-1",
            "VPCId": "vpc-0f11d467dd89ac123"
        }
    ]
}
```
It is used for private DNS within a given VPC. In order to support this the operator needs to deal with the fact that VPC is there instead of nameservers

This issue was created upon request in this slack thread:
https://kubernetes.slack.com/archives/C05J0D0V525/p1710844895665569

**Comment by philbrookes** [comment]
could be resolved by: https://github.com/Kuadrant/dns-operator/issues/60

**Comment by trepel** [comment]
> could be resolved by: #60

Could be but not necessarily. That one is more about "fail gracefully if NameServers are not present" rather than "support private Hosted Zones (which have VPCs rather than NameServers)"

**Comment by maleck13** [comment]
The nameservers are not actually used other than to put them into the status. So it is possible that fixing the bug would allow the zone to be created and used. We would just be misssing the VPC info in the status which shouldn't cause any issues

**Comment by philbrookes** [comment]
can be completed by running the e2e tests against a private AWS Route53 Zone

**Comment by maleck13** [comment]
@trepel marking as done. 
![Image](https://github.com/user-attachments/assets/b6136425-059c-46e4-97fb-dfa9759acd94)

I was able to create records against a private zone now
